const form=document.querySelector("form")
const previous=document.querySelector(".guesses")

const remaining=document.querySelector(".lastResult")

// random number generated by computer 
// value inside input 

form.addEventListener("submit", (e)=>{
e.preventDefault();

console.log(e.id)

})